server:
  port: 8099

eureka: #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka} # Registers the Gateway in Eureka Server

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true #Enable de locator for the services in Eureka Server (Registry Discovery)
      routes:
        - id: persona-service
          uri: lb://persona-service #Persona service route declaration
          predicates:
            - Path=/persona/** #Path to access the service
          filters:
            - StripPrefix=1

        - id: solicitud-service
          uri: lb://solicitud-service #Solicitud service route declaration
          predicates:
            - Path=/solicitud/** #Path to access the service
          filters:
            - StripPrefix=1