server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service
          uri: http://localhost:8081/
          predicates:
            - Path=/persona/**
        - id: solicitud-service
          uri: https://localhost:8081/
          predicates:
            - Path=/solicitud/**